//{{NO_DEPENDENCIES}}
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_OpenS100TYPE                130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_CREATE_AUTO_RELATION 307
#define IDR_TOOLBAR1                    310
#define IDD_DIALOG_DOCK_LAYERMANEGER    312
#define IDR_TOOLBAR2                    312
#define IDD_DIALOG_DOCK_RELATION        313
#define IDD_DIALOG_DOCK_CURRENT_SELECTION 314
#define IDD_DIALOG_DOCK_LOGGER          315
#define IDC_LIST_RELATION               317
#define IDR_HELP_MENU                   317
#define IDC_LIST_CURRENT_SELECTION      318
#define IDC_BUTTON_LISTCLEAR            319
#define IDC_COMBO_LOG_TYPE              320
#define IDB_PNG1                        320
#define IDC_LIST_LOGGER                 321
#define IDC_CUR_GRAB                    321
#define T1                              322
#define IDC_CUR_PEN                     322
#define T2                              323
#define IDC_CURSOR_ZOOM_AREA            323
#define T3                              324
#define IDD_DIALOG1                     324
#define IDD_DIALOG_NOGEOMETRY           324
#define T4                              325
#define T5                              326
#define IDD_DIALOG_INFORMATIONTYPE      326
#define T6                              327
#define IDB_PNG2                        327
#define IDB_PICK_ARROW_PNG              327
#define T7                              328
#define T8                              329
#define T9                              330
#define T10                             331
#define T11                             332
#define T12                             333
#define IDR_TOOLBAR3                    334
#define IDC_LIST_LM                     335
#define IDB_BITMAP1                     336
#define IDC_DIALOG_DOCK_PROPERTI        338
#define IDC_LIST_NOGEOMETRY             339
#define IDC_LIST_INFORMATIONTYPE        340
#define IDC_PROPERTY_GRID_VECTOR        341
#define IDC_PROPERTY_GRID_ATTRIBUTE     342
#define IDB_BITMAP3                     343
#define IDD_DIALOG_CONFIG               344
#define IDD_DIALOG_CONFIG_1             345
#define IDC_CONFIG_TAB                  346
#define IDC_APPLY                       347
#define IDD_DIALOG_CONFIG_4             348
#define IDC_LIST_VIEWINGGROUP           349
#define IDC_BUTTON1                     350
#define IDC_TWO_SHADE                   351
#define IDC_BTN_LOAD_SETTING            352
#define IDC_COMBO_SETTING_FONT_NAME     561
#define IDC_RADIO_OTHER                 1036
#define IDC_COLOR_DUSK_WB               1040
#define IDC_DPM_STANDARD                1081
#define IDC_SAFETY_WATER_LEVEL          1083
#define IDC_VERY_SHALLOW_WATER          1084
#define IDC_DEPTH_CORRECTION_INTERVAL   1086
#define IDC_COLOR_DB                    1087
#define IDC_SEABED_SYMPLIFIED           1092
#define IDC_S101_SYMBOL_1               1093
#define IDC_SEABED_FULL_TEXT            1095
#define IDC_COLOR_NIGHT                 1114
#define IDC_USE_NOBJNM                  1119
#define IDC_DPM_BASE                    1128
#define IDC_DPM_OTHERS                  1153
#define IDC_VERY_DEEP_WATER             1154
#define IDC_SAFETY_DEPTH                1162
#define IDC_CHECK_SHOW_ISOLATED_DANGER  1209
#define IDC_INTEND_TO_PERFORMANCE       1217
#define IDC_CHECK2                      1349
#define IDC_CHECK1                      1351
#define IDC_CHECK4                      1352
#define IDC_CHECK_SIMPLIFY_LINE         1353
#define IDC_CHECK_FULL_LIGHT_SECTOR     1354
#define IDC_CHECK7                      1355
#define IDC_EDIT_SETTING_FONT_SIZE      1360
#define IDC_CHECK_IGNORE_SCALE_MIN      1369
#define IDC_CHECK_SHALLOW_PATTERN       1370
#define IDC_CHECK_SIMPLIFY_POINT        1371
#define IDC_CHECK_SHOW_INFORM01         1375
#define IDC_CHECK_S111_SHOW_NODATA      1380
#define IDC_STATIC_TEXTGROUP            1382
#define IDC_RADIO_LIGHT                 1383
#define IDC_RADIO_IMPORTANT             1384
#define ID_BUTTON32771                  32771
#define ID_BUTTON32772                  32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
